### ISSUE TITLE
UnauthorizedUserError

### ISSUE THREAD

**Issue by folliefollie721** [microsoft/openpaivscode#23]
After I edit the configuration and click finish to save ,  I got this error message: 
载入任务列表时发生错误：401 - "{\"code\":\"UnauthorizedUserError\",\"message\":\"Guest is not allowed to do this operation.\"}"
Is it a problem of insufficient permissions on the server?

**Comment by yiyione** [comment]
Hi @folliefollie721 
It's the token authorization error when loading the job list.
1. Please make sure you are using the last version of the `OpenPAI VSCode Client >=0.3.2`, the old version Client may not sent the access token to the OpenPAI server and got this error.
2. If you are using password for authorization, please make sure remove the `"token"` field in the configuration.

**Comment by folliefollie721** [comment]
@yiyione Thank you very much for your answers!  I checked the version of the` OpenPAI VSCode Client `and the version is` 0.3.2`. I was using password for authorization, so I remove the` "token"` field.  However, it still reported this error. Then I removed the` https`field, it can load job list.  But in the process I used the extension it always reportes this error which is` failed to load job list: 401 - "{\"code\":\"UnauthorizedUserError\",\"message\":\"Guest is not allowed to do this operation.\"}"`

**Comment by yiyione** [comment]
@folliefollie721 Can you try to remove the PAI cluster in VSCode, and re-add it ?
If still got this error, you can try to use the application token for authorization.

![applicationToken](https://user-images.githubusercontent.com/17357108/89733750-423f2d00-da8a-11ea-8397-e15f1c2e37e5.png)

**Comment by folliefollie721** [comment]
@yiyione  I tried to remove and  re-add  the PAI cluster in VSCode, but still got this error.   I used the application token for authorization, it works for me. Thank you for your apply!
